name: publish

on: [push]

jobs:
  master_push_to_registry:
    name: Push Docker image to GitHub Packages as with Tag 'latest'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./
          dockerfile: ./Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: protomaps/go-pmtiles
          tags: master
          platforms: linux/amd64,linux/arm64,linux/arm/v7
